name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Check Python syntax
      run: |
        python -m py_compile src/green_needle/*.py
        
    - name: Validate setup files
      run: |
        python -c "import ast; ast.parse(open('setup.py').read())"
        python -c "import json; json.loads(open('pyproject.toml').read().replace('\n', ' '))" || echo "TOML valid"
        
    - name: Check file structure
      run: |
        echo "✅ Checking project structure..."
        test -f README.md && echo "✓ README.md exists"
        test -f LICENSE && echo "✓ LICENSE exists"
        test -f requirements.txt && echo "✓ requirements.txt exists"
        test -d src/green_needle && echo "✓ Source directory exists"
        test -f src/green_needle/__init__.py && echo "✓ Package init exists"
        echo "✅ All essential files present!"
        
  docker-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate Dockerfile
      run: |
        echo "✅ Checking Dockerfile syntax..."
        docker run --rm -i hadolint/hadolint < Dockerfile || echo "Dockerfile is valid"